spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:codebattlearena-secret-key-2025-very-long-and-secure-key}
  expiration: 86400000

ai:
  openai:
    api-key: ${OPENAI_API_KEY:}

upload:
  path: ./uploads

logging:
  level:
    com.codebattlearena: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
