spring:
  application:
    name: CodeBattleArena
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:codebattlearena-secret-key-2025-very-long-and-secure-key}
  expiration: 86400000

openai:
  api:
    key: ${OPENAI_API_KEY:}

cloudinary:
  url: ${CLOUDINARY_URL:}