spring:
  application:
    name: CodeBattleArena
  
  datasource:
    url: jdbc:postgresql://localhost:5432/codebattlearena
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  websocket:
    allowed-origins: "*"

server:
  port: 8080

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
