spring:
  application:
    name: CodeBattleArena
  
  datasource:
    url: jdbc:postgresql://localhost:5433/codebattlearena
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

jwt:
  secret: codebattlearena-secret-key-2025-very-long-and-secure-key
  expiration: 86400000

logging:
  level:
    com.codebattlearena: DEBUG
    org.springframework.security: WARN
    org.springframework.web: WARN